### ISSUE TITLE
Minor fixes

### ISSUE THREAD

**Issue by DominiqueMakowski** [Sussex-Psychology-Software-Team/DoggoNogo#5]
- [x] randomID 

In our pilots `randomID` is always the same: 
![image](https://github.com/user-attachments/assets/0d40d697-1468-4764-bb19-078814815250)

Could it be a seed issue?

- [x] Pilots are reporting that the first screen "You are an investigator tasked with blabla" is slightly too short, can we lave it like 1 second longer?

**Comment by DominiqueMakowski** [comment]
But it works for the filename?

![image](https://github.com/user-attachments/assets/fc3f1d19-38b5-437a-ad2f-1e09d52f889c)


Also, maybe we should rename randomID to `sessionID` because it will act as the identifier of a unique session in case of replays

Also, maybe this sessionID could contain the date so that we ensure that it's near-always unique? 

Like 7 randomstring + datetime: `mK5HoLT04112024` (note the 04/11/2024)

@BenjaminTribe

**Comment by Max-Lovell** [comment]
I've increased all the screens to 4 seconds as it was all using 1 var. lmk if you think it feels off anywhere and I can handle them individually.

The random ID issue also affects the startDate (and potentially screen size) fields FYI - something I missed about Unity's 'field serialisation' is that the values are stored in the editor if initialised in the class constructor.... anyway, should be fixed now.

As for loading screen, are you sure you want to prioritise loading speed over runtime speed? Also, are you thinking of Asset Bundles? There is stuff you can do with build settings but these are kind of hidden away by gameCI... might be something I can do about it though: https://game.ci/docs/github/builder#configuration-options. Can give load speed another look soon.

Instead of an initial blank background would be nice to have a loading screen. I bet it'll be a pain as it will be inside the HTML template and not unity, but useful when done properly. Once I've got enough of these solutions we could think about some sort of unity package (unityPsych) that sets up a project with the functions you'd tend to need already available.

**Comment by DominiqueMakowski** [comment]
from 1s to 4? Might be too long no? I think it's really just the first one that has the longest text and once they are engaged they can read the rest. I'd say to change the first from 1 -> 2 and leave the rest as is

For the loading screen we'll see how it goes, my guess is that it will only become a problem in the future once the game is heavier and have more assets

**Comment by Max-Lovell** [comment]
Each slide was up for 3 seconds previously, so just added a second - I think it works just as well tbf

**Comment by DominiqueMakowski** [comment]
alright then cheers!
